name: Deploy dist
on: push
jobs:
  run: |
    echo "Cloning the repository..."
    echo "Repo: ${{github.repository}}"
    git clone https://github.com/${{github.repository}}.git myfiles
    cd myfiles && ls
